import ElementComponent from "./ElementComponent";
import { useState } from "react";
import gridStyling from "./grid.scss";

export default function PeriodicTable({periodicTable}) {
  return (
    <div className="PeriodicTable" style={{ gridStyling }}>
      <div className="grid-container-1">
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
      </div>
      <div className="grid-container-2">
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
        <ElementComponent />
      </div>
    </div>
  );
}
